### ISSUE TITLE
Overscroll is displayed under the header

### ISSUE THREAD

**Issue by Kernald** [blipinsk/RecyclerViewHeader#17]
When the header doesn't use the full width of the `RecyclerView`, the overscroll effect (colored "wave") is visible under the header. It should idealy be on top of it.

**Comment by blipinsk** [comment]
Since the overscroll indicator is the part of the scrollable element (`RecyclerView`), and the `RecyclerViewHeader` is being hovered on top of it, this won't be possible. There is no way (at least that I know of) to move the overscroll indicator z-order wise.

There are two half measures you can take (they won't solve the problem - since it's kinda unsolvable - but will hide it):

a) If your header does not have to be clickable (there are no `Buttons`, `EditTexts`, etc.), you can use the "Header-already-aligned approach", and put the `RecyclerViewHeader` below (z-wise) the `RecyclerView`. In this approach your `RecyclerView` must have a transparent background.

b) Just disable your `RecyclerView's` overscroll effect by setting the following for your `RecyclerView`:

    android:overScrollMode="never"
