### ISSUE TITLE
when using scrollToPosition

### ISSUE THREAD

**Issue by Ivolian** [blipinsk/RecyclerViewHeader#34]
When using scrollToPosition method, the head view appear in wrong position.

**Comment by osama-raddad** [comment]
yes i have this issue to

**Comment by blipinsk** [comment]
The `RecyclerViewHeader` uses `ScrollListener` to move the `header`. The problem is, there is a [known issue of the `RecyclerView`](http://stackoverflow.com/questions/27819507/recyclerview-scrolltoposition-not-trigger-scrolllistener) in which the `ScrollListener` is not getting called when using `scrollToPosition`. So I kinda have no way to overcome this issue as it's buried deep inside the `RecyclerView` logic.
