### ISSUE TITLE
Why not add a footer

### ISSUE THREAD

**Issue by sungerk** [blipinsk/RecyclerViewHeader#48]

**Comment by blipinsk** [comment]
Hi,
if the footer is the only thing you want (you don't need a header at the same time), you can use this library with the reverse order layout manager.

I do not plan to add a separate component - the footer, mostly because this library is not in an active development anymore. I do not plan to implement any enhancements - only bug fixes.

Thanks for the suggestion, though.

Cheers,
Bartek
