### ISSUE TITLE
 How to add scroll for the header?

### ISSUE THREAD

**Issue by kamilwlf** [blipinsk/RecyclerViewHeader#8]
I can scroll through the list just by touching a list item, I cant scroll touching the header. My heading is wiget scrolled horizontally.

Can you advise something?

**Comment by trolik** [comment]
Same same

**Comment by kamilwlf** [comment]
I would like to mention that migration to listview 
solves all problems

**Comment by blipinsk** [comment]
So does reading [**Limitations** ](https://github.com/blipinsk/RecyclerViewHeader/blob/master/README.md#limitations) section of **Readme** and following instructions (using a different adapter) for trying to implement things "outside limitations" . Migrating back to `ListView` is a pretty bad idea since the whole `Android` world is moving toward using `RecyclerView` instead of the "old" `ListView` and `GridView`.

**Comment by kamilwlf** [comment]
I agree, when you need to customize your list(LayoutManager e.q Grid, Decoration) or you want better animations, but I do not see any other advantages.
in 80% of cases there is no profit

**Comment by blipinsk** [comment]
It's an age-old question whether you should use a `RecyclerView` or a `ListView`. If you manage to correctly write your `ListView` adapter there won't be any advantages over the `RecyclerView` (excluding those animations maybe). `RecyclerView` "forces" you to use the right approach (the `ViewHolder` base), the `ListView` doesn't. You can much easier mess a `ListView` adapter than a `RecyclerView` adapter.
